### PR TITLE
accommodate new grid unit implementation while still working for old …

### PR DESCRIPTION
**Pull request by pmur002**
…grid units.

This is an attempt to provide a "fix" for new grid units that can be submitted to CRAN whenever you are ready.

This relates to issue https://github.com/eliocamp/metR/issues/104

### CODE REVIEW

**Comment by eliocamp** [comment]
Thanks!

**Comment by pmur002** [comment]
Great.  Thank you.  For our planning, are you able to give us any idea on when a new 'metR' version might be submitted to CRAN ?

**Comment by eliocamp** [comment]
It's already on its way :flight_departure:

**Comment by pmur002** [comment]
Awesome.  Thanks!

**Comment by eliocamp** [comment]
No problem at all. 
Thanks to you for the work on the grid package :tada:

**Pull request merged**
